replicaCount: 1

image:
  repository: onthelink/the-waiting-timer
  tag: {{ .Chart.AppVersion }}
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: nginx
  host: timer.local
  annotations: {}
  tls: []

persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce

resources: {}

timerName: "something"
